version: "2.1"

services:
  backend:
    build:
      context: ./backend
    ports: 
      - "5000:5000"
    restart: unless-stopped

  mysql-master:
    image: mysql:8.0
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vot
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./database/master.cnf:/etc/mysql/my.cnf
      - ./database/src:/docker-entrypoint-db.d 
  
  mysql-slave:
    image: mysql:8.0
    restart: always
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vot
    volumes:
      - mysql_slave_data:/var/lib/mysql
      - ./database/slave.cnf:/etc/mysql/my.cnf
      - ./database/src:/docker-entrypoint-db.d 
    depends_on:
      - mysql-master

  proxysql:
    image: proxysql/proxysql:latest
    restart: always
    ports:
      - "6032:6032"
      - "6033:6033"
    volumes:
      - ./database/proxy.cnf:/etc/proxy.cnf
      - ./database/src/proxy.sql:/docker-entrypoint-initdb.d/proxy.sql
    command: ["sh", "-c", "proxysql --initial -f /etc/proxy.cnf && sleep 10 && mysql -u admin -p admin -h 127.0.0.1 -P 6032 < /docker-entrypoint-db.d/proxy_init.sql"]

volumes:
  mysql_master_data:
  mysql_slave_data: